[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = false
chain_id = 56
auto_detect_solc = false
solc_version = "0.8.11"
evm_version = "london"
optimizer = true
optimizer_runs = 200
libraries = []
rpc_endpoints = { base = "https://1rpc.io/base" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options