[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
auto_detect_remappings = true
chain_id = 56
auto_detect_solc = true
# solc_version = ["0.8.11", "0.8.20"]
# evm_version = "london"
optimizer = true
optimizer_runs = 200
libraries = []
rpc_endpoints = { base = "https://base.llamarpc.com", local = "http://127.0.0.1:8545" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options